# Project information
site_name: Tcl Knowledge Base
site_description: 🪶 Knowledge Base (KB) for developers who are using the Tcl (Tool Command Language) programming language.
site_author: Hsins
site_url: https://hsins.github.io/TclKB

# Repository
repo_name: Hsins/TclKB
repo_url: https://github.com/Hsins/TclKB
edit_uri: edit/docs/docs/

# Copyright
copyright: Copyright &copy; 2021 Hsins

# Configuration
theme:
  name: material
  custom_dir: overrides

  # Static files
  static_templates:
    - 404.html

  # Don't include Mkdocs JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    # Light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github-square
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Contents
nav:
  - Home: index.md
  - Setup:
      - Overview: setup/index.md
  - Tutorial:
      - Overview: tutorial/index.md

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - i18n:
      default_language: en
      languages:
        en: English
        zh: 繁體中文
      nav_translations:
        zh:
          Home: 首頁
          Setup: 安裝
          Tutorial: 教學
          Overview: 概述

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hsins

extra_javascript:
  # MathJax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - extra/js/config.js
  # Tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - extra/js/tables.js
  # Han
  #- https://cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.js

extra_css:
  - extra/css/home.css
  #- https://cdnjs.cloudflare.com/ajax/libs/Han/3.3.0/han.min.css
